package hibernate.entities;
// Generated 13 nov. 2018 17:17:38 by Hibernate Tools 4.3.1


import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Articles generated by hbm2java
 */
@Entity
@Table(name="articles"
    ,catalog="flyinpizzas_mdabase"
)
public class Articles  implements java.io.Serializable {

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "weborderLinesArticleId")
    private Collection<WeborderLines> weborderLinesCollection;


    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="article_id", nullable=false)
     private Integer articleId;
@ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="article_colors_id", nullable=false)
     private Colors colors;
@Column(name="article_size", nullable=false, length=6)
     private String articleSize;
@Column(name="article_gencod", nullable=false, length=13)
     private String articleGencod;
@Column(name="article_key", nullable=false, length=20)
     private String articleKey;
@OneToMany(fetch=FetchType.LAZY, mappedBy="articles")
     private Set<Stocks> stockses = new HashSet<Stocks>(0);

    public Articles() {
    }

	
    public Articles(Colors colors, String articleSize, String articleGencod, String articleKey) {
        this.colors = colors;
        this.articleSize = articleSize;
        this.articleGencod = articleGencod;
        this.articleKey = articleKey;
    }
    public Articles(Colors colors, String articleSize, String articleGencod, String articleKey, Set<Stocks> stockses) {
       this.colors = colors;
       this.articleSize = articleSize;
       this.articleGencod = articleGencod;
       this.articleKey = articleKey;
       this.stockses = stockses;
    }
   
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Colors getColors() {
        return this.colors;
    }
    
    public void setColors(Colors colors) {
        this.colors = colors;
    }

    
    public String getArticleSize() {
        return this.articleSize;
    }
    
    public void setArticleSize(String articleSize) {
        this.articleSize = articleSize;
    }

    
    public String getArticleGencod() {
        return this.articleGencod;
    }
    
    public void setArticleGencod(String articleGencod) {
        this.articleGencod = articleGencod;
    }

    
    public String getArticleKey() {
        return this.articleKey;
    }
    
    public void setArticleKey(String articleKey) {
        this.articleKey = articleKey;
    }

    public Set<Stocks> getStockses() {
        return this.stockses;
    }
    
    public void setStockses(Set<Stocks> stockses) {
        this.stockses = stockses;
    }

    @XmlTransient
    public Collection<WeborderLines> getWeborderLinesCollection() {
        return weborderLinesCollection;
    }

    public void setWeborderLinesCollection(Collection<WeborderLines> weborderLinesCollection) {
        this.weborderLinesCollection = weborderLinesCollection;
    }




}


