package hibernate.entities;
// Generated 12 oct. 2018 17:49:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Articles generated by hbm2java
 */
@Entity
@Table(name="articles"
    ,catalog="flyinpizzas_mdabase"
    , uniqueConstraints = @UniqueConstraint(columnNames={"article_colors_id", "article_size"}) 
)
public class Articles  implements java.io.Serializable {


     private Integer articleId;
     private Colors colors;
     private String articleSize;
     private String articleGencod;
     private String articleKey;
     private Set stockses = new HashSet(0);

    public Articles() {
    }

	
    public Articles(Colors colors, String articleSize, String articleGencod, String articleKey) {
        this.colors = colors;
        this.articleSize = articleSize;
        this.articleGencod = articleGencod;
        this.articleKey = articleKey;
    }
    public Articles(Colors colors, String articleSize, String articleGencod, String articleKey, Set stockses) {
       this.colors = colors;
       this.articleSize = articleSize;
       this.articleGencod = articleGencod;
       this.articleKey = articleKey;
       this.stockses = stockses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="article_id", unique=true, nullable=false)
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="article_colors_id", nullable=false)
    public Colors getColors() {
        return this.colors;
    }
    
    public void setColors(Colors colors) {
        this.colors = colors;
    }

    
    @Column(name="article_size", nullable=false, length=6)
    public String getArticleSize() {
        return this.articleSize;
    }
    
    public void setArticleSize(String articleSize) {
        this.articleSize = articleSize;
    }

    
    @Column(name="article_gencod", nullable=false, length=13)
    public String getArticleGencod() {
        return this.articleGencod;
    }
    
    public void setArticleGencod(String articleGencod) {
        this.articleGencod = articleGencod;
    }

    
    @Column(name="article_key", nullable=false, length=20)
    public String getArticleKey() {
        return this.articleKey;
    }
    
    public void setArticleKey(String articleKey) {
        this.articleKey = articleKey;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="articles")
    public Set getStockses() {
        return this.stockses;
    }
    
    public void setStockses(Set stockses) {
        this.stockses = stockses;
    }




}


