package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1



/**
 * CodeColors generated by hbm2java
 */
public class CodeColors  implements java.io.Serializable {


     private Integer codeColorsId;
     private String codeColorsCode;
     private String codeColorsDesignation;

    public CodeColors() {
    }

    public CodeColors(String codeColorsCode, String codeColorsDesignation) {
       this.codeColorsCode = codeColorsCode;
       this.codeColorsDesignation = codeColorsDesignation;
    }
   
    public Integer getCodeColorsId() {
        return this.codeColorsId;
    }
    
    public void setCodeColorsId(Integer codeColorsId) {
        this.codeColorsId = codeColorsId;
    }
    public String getCodeColorsCode() {
        return this.codeColorsCode;
    }
    
    public void setCodeColorsCode(String codeColorsCode) {
        this.codeColorsCode = codeColorsCode;
    }
    public String getCodeColorsDesignation() {
        return this.codeColorsDesignation;
    }
    
    public void setCodeColorsDesignation(String codeColorsDesignation) {
        this.codeColorsDesignation = codeColorsDesignation;
    }




}


