package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Colors generated by hbm2java
 */
public class Colors  implements java.io.Serializable {


     private Integer colorsId;
     private Models models;
     private String colorsCode;
     private String colorsLibelle;
     private Set articleses = new HashSet(0);

    public Colors() {
    }

	
    public Colors(Models models, String colorsCode, String colorsLibelle) {
        this.models = models;
        this.colorsCode = colorsCode;
        this.colorsLibelle = colorsLibelle;
    }
    public Colors(Models models, String colorsCode, String colorsLibelle, Set articleses) {
       this.models = models;
       this.colorsCode = colorsCode;
       this.colorsLibelle = colorsLibelle;
       this.articleses = articleses;
    }
   
    public Integer getColorsId() {
        return this.colorsId;
    }
    
    public void setColorsId(Integer colorsId) {
        this.colorsId = colorsId;
    }
    public Models getModels() {
        return this.models;
    }
    
    public void setModels(Models models) {
        this.models = models;
    }
    public String getColorsCode() {
        return this.colorsCode;
    }
    
    public void setColorsCode(String colorsCode) {
        this.colorsCode = colorsCode;
    }
    public String getColorsLibelle() {
        return this.colorsLibelle;
    }
    
    public void setColorsLibelle(String colorsLibelle) {
        this.colorsLibelle = colorsLibelle;
    }
    public Set getArticleses() {
        return this.articleses;
    }
    
    public void setArticleses(Set articleses) {
        this.articleses = articleses;
    }




}


