package hibernate.entities;
// Generated 12 oct. 2018 17:49:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Colors generated by hbm2java
 */
@Entity
@Table(name="colors"
    ,catalog="flyinpizzas_mdabase"
    , uniqueConstraints = @UniqueConstraint(columnNames={"colors_model_id", "colors_code"}) 
)
public class Colors  implements java.io.Serializable {


     private Integer colorsId;
     private Models models;
     private String colorsCode;
     private String colorsLibelle;
     private Set articleses = new HashSet(0);

    public Colors() {
    }

	
    public Colors(Models models, String colorsCode, String colorsLibelle) {
        this.models = models;
        this.colorsCode = colorsCode;
        this.colorsLibelle = colorsLibelle;
    }
    public Colors(Models models, String colorsCode, String colorsLibelle, Set articleses) {
       this.models = models;
       this.colorsCode = colorsCode;
       this.colorsLibelle = colorsLibelle;
       this.articleses = articleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="colors_id", unique=true, nullable=false)
    public Integer getColorsId() {
        return this.colorsId;
    }
    
    public void setColorsId(Integer colorsId) {
        this.colorsId = colorsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="colors_model_id", nullable=false)
    public Models getModels() {
        return this.models;
    }
    
    public void setModels(Models models) {
        this.models = models;
    }

    
    @Column(name="colors_code", nullable=false, length=5)
    public String getColorsCode() {
        return this.colorsCode;
    }
    
    public void setColorsCode(String colorsCode) {
        this.colorsCode = colorsCode;
    }

    
    @Column(name="colors_libelle", nullable=false, length=50)
    public String getColorsLibelle() {
        return this.colorsLibelle;
    }
    
    public void setColorsLibelle(String colorsLibelle) {
        this.colorsLibelle = colorsLibelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="colors")
    public Set getArticleses() {
        return this.articleses;
    }
    
    public void setArticleses(Set articleses) {
        this.articleses = articleses;
    }




}


