package hibernate.entities;
// Generated 10 oct. 2018 14:43:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GridSize generated by hbm2java
 */
@Entity
@Table(name="grid_size"
    ,catalog="flyinpizzas_mdabase"
)
public class GridSize  implements java.io.Serializable {


     private Integer gridSizeId;
     private String gridSizeName;
     private String gs01;
     private String gs02;
     private String gs03;
     private String gs04;
     private String gs05;
     private String gs06;
     private String gs07;
     private String gs08;
     private String gs09;
     private String gs10;
     private String gs11;
     private String gs12;
     private String gs13;
     private String gs14;
     private String gs15;
     private String gs16;
     private String gs17;
     private String gs18;
     private String gs19;
     private String gs20;
     private Set modelses = new HashSet(0);

    public GridSize() {
    }

	
    public GridSize(String gridSizeName, String gs01, String gs02, String gs03, String gs04, String gs05, String gs06, String gs07, String gs08, String gs09, String gs10, String gs11, String gs12, String gs13, String gs14, String gs15, String gs16, String gs17, String gs18, String gs19, String gs20) {
        this.gridSizeName = gridSizeName;
        this.gs01 = gs01;
        this.gs02 = gs02;
        this.gs03 = gs03;
        this.gs04 = gs04;
        this.gs05 = gs05;
        this.gs06 = gs06;
        this.gs07 = gs07;
        this.gs08 = gs08;
        this.gs09 = gs09;
        this.gs10 = gs10;
        this.gs11 = gs11;
        this.gs12 = gs12;
        this.gs13 = gs13;
        this.gs14 = gs14;
        this.gs15 = gs15;
        this.gs16 = gs16;
        this.gs17 = gs17;
        this.gs18 = gs18;
        this.gs19 = gs19;
        this.gs20 = gs20;
    }
    public GridSize(String gridSizeName, String gs01, String gs02, String gs03, String gs04, String gs05, String gs06, String gs07, String gs08, String gs09, String gs10, String gs11, String gs12, String gs13, String gs14, String gs15, String gs16, String gs17, String gs18, String gs19, String gs20, Set modelses) {
       this.gridSizeName = gridSizeName;
       this.gs01 = gs01;
       this.gs02 = gs02;
       this.gs03 = gs03;
       this.gs04 = gs04;
       this.gs05 = gs05;
       this.gs06 = gs06;
       this.gs07 = gs07;
       this.gs08 = gs08;
       this.gs09 = gs09;
       this.gs10 = gs10;
       this.gs11 = gs11;
       this.gs12 = gs12;
       this.gs13 = gs13;
       this.gs14 = gs14;
       this.gs15 = gs15;
       this.gs16 = gs16;
       this.gs17 = gs17;
       this.gs18 = gs18;
       this.gs19 = gs19;
       this.gs20 = gs20;
       this.modelses = modelses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="grid_size_id", unique=true, nullable=false)
    public Integer getGridSizeId() {
        return this.gridSizeId;
    }
    
    public void setGridSizeId(Integer gridSizeId) {
        this.gridSizeId = gridSizeId;
    }

    
    @Column(name="grid_size_name", nullable=false, length=20)
    public String getGridSizeName() {
        return this.gridSizeName;
    }
    
    public void setGridSizeName(String gridSizeName) {
        this.gridSizeName = gridSizeName;
    }

    
    @Column(name="GS01", nullable=false, length=6)
    public String getGs01() {
        return this.gs01;
    }
    
    public void setGs01(String gs01) {
        this.gs01 = gs01;
    }

    
    @Column(name="GS02", nullable=false, length=6)
    public String getGs02() {
        return this.gs02;
    }
    
    public void setGs02(String gs02) {
        this.gs02 = gs02;
    }

    
    @Column(name="GS03", nullable=false, length=6)
    public String getGs03() {
        return this.gs03;
    }
    
    public void setGs03(String gs03) {
        this.gs03 = gs03;
    }

    
    @Column(name="GS04", nullable=false, length=6)
    public String getGs04() {
        return this.gs04;
    }
    
    public void setGs04(String gs04) {
        this.gs04 = gs04;
    }

    
    @Column(name="GS05", nullable=false, length=6)
    public String getGs05() {
        return this.gs05;
    }
    
    public void setGs05(String gs05) {
        this.gs05 = gs05;
    }

    
    @Column(name="GS06", nullable=false, length=6)
    public String getGs06() {
        return this.gs06;
    }
    
    public void setGs06(String gs06) {
        this.gs06 = gs06;
    }

    
    @Column(name="GS07", nullable=false, length=6)
    public String getGs07() {
        return this.gs07;
    }
    
    public void setGs07(String gs07) {
        this.gs07 = gs07;
    }

    
    @Column(name="GS08", nullable=false, length=6)
    public String getGs08() {
        return this.gs08;
    }
    
    public void setGs08(String gs08) {
        this.gs08 = gs08;
    }

    
    @Column(name="GS09", nullable=false, length=6)
    public String getGs09() {
        return this.gs09;
    }
    
    public void setGs09(String gs09) {
        this.gs09 = gs09;
    }

    
    @Column(name="GS10", nullable=false, length=6)
    public String getGs10() {
        return this.gs10;
    }
    
    public void setGs10(String gs10) {
        this.gs10 = gs10;
    }

    
    @Column(name="GS11", nullable=false, length=6)
    public String getGs11() {
        return this.gs11;
    }
    
    public void setGs11(String gs11) {
        this.gs11 = gs11;
    }

    
    @Column(name="GS12", nullable=false, length=6)
    public String getGs12() {
        return this.gs12;
    }
    
    public void setGs12(String gs12) {
        this.gs12 = gs12;
    }

    
    @Column(name="GS13", nullable=false, length=6)
    public String getGs13() {
        return this.gs13;
    }
    
    public void setGs13(String gs13) {
        this.gs13 = gs13;
    }

    
    @Column(name="GS14", nullable=false, length=6)
    public String getGs14() {
        return this.gs14;
    }
    
    public void setGs14(String gs14) {
        this.gs14 = gs14;
    }

    
    @Column(name="GS15", nullable=false, length=6)
    public String getGs15() {
        return this.gs15;
    }
    
    public void setGs15(String gs15) {
        this.gs15 = gs15;
    }

    
    @Column(name="GS16", nullable=false, length=6)
    public String getGs16() {
        return this.gs16;
    }
    
    public void setGs16(String gs16) {
        this.gs16 = gs16;
    }

    
    @Column(name="GS17", nullable=false, length=6)
    public String getGs17() {
        return this.gs17;
    }
    
    public void setGs17(String gs17) {
        this.gs17 = gs17;
    }

    
    @Column(name="GS18", nullable=false, length=6)
    public String getGs18() {
        return this.gs18;
    }
    
    public void setGs18(String gs18) {
        this.gs18 = gs18;
    }

    
    @Column(name="GS19", nullable=false, length=6)
    public String getGs19() {
        return this.gs19;
    }
    
    public void setGs19(String gs19) {
        this.gs19 = gs19;
    }

    
    @Column(name="GS20", nullable=false, length=6)
    public String getGs20() {
        return this.gs20;
    }
    
    public void setGs20(String gs20) {
        this.gs20 = gs20;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gridSize")
    public Set getModelses() {
        return this.modelses;
    }
    
    public void setModelses(Set modelses) {
        this.modelses = modelses;
    }




}


