package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Models generated by hbm2java
 */
public class Models  implements java.io.Serializable {


     private Integer modelId;
     private GridSize gridSize;
     private Seasons seasons;
     private String modelModel;
     private String modelDesignation;
     private Set colorses = new HashSet(0);

    public Models() {
    }

	
    public Models(GridSize gridSize, Seasons seasons, String modelModel, String modelDesignation) {
        this.gridSize = gridSize;
        this.seasons = seasons;
        this.modelModel = modelModel;
        this.modelDesignation = modelDesignation;
    }
    public Models(GridSize gridSize, Seasons seasons, String modelModel, String modelDesignation, Set colorses) {
       this.gridSize = gridSize;
       this.seasons = seasons;
       this.modelModel = modelModel;
       this.modelDesignation = modelDesignation;
       this.colorses = colorses;
    }
   
    public Integer getModelId() {
        return this.modelId;
    }
    
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }
    public GridSize getGridSize() {
        return this.gridSize;
    }
    
    public void setGridSize(GridSize gridSize) {
        this.gridSize = gridSize;
    }
    public Seasons getSeasons() {
        return this.seasons;
    }
    
    public void setSeasons(Seasons seasons) {
        this.seasons = seasons;
    }
    public String getModelModel() {
        return this.modelModel;
    }
    
    public void setModelModel(String modelModel) {
        this.modelModel = modelModel;
    }
    public String getModelDesignation() {
        return this.modelDesignation;
    }
    
    public void setModelDesignation(String modelDesignation) {
        this.modelDesignation = modelDesignation;
    }
    public Set getColorses() {
        return this.colorses;
    }
    
    public void setColorses(Set colorses) {
        this.colorses = colorses;
    }




}


