package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Places generated by hbm2java
 */
public class Places  implements java.io.Serializable {


     private Integer placeId;
     private String placeName;
     private String placeDesignation;
     private Set stockses = new HashSet(0);

    public Places() {
    }

	
    public Places(String placeName, String placeDesignation) {
        this.placeName = placeName;
        this.placeDesignation = placeDesignation;
    }
    public Places(String placeName, String placeDesignation, Set stockses) {
       this.placeName = placeName;
       this.placeDesignation = placeDesignation;
       this.stockses = stockses;
    }
   
    public Integer getPlaceId() {
        return this.placeId;
    }
    
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }
    public String getPlaceName() {
        return this.placeName;
    }
    
    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }
    public String getPlaceDesignation() {
        return this.placeDesignation;
    }
    
    public void setPlaceDesignation(String placeDesignation) {
        this.placeDesignation = placeDesignation;
    }
    public Set getStockses() {
        return this.stockses;
    }
    
    public void setStockses(Set stockses) {
        this.stockses = stockses;
    }




}


