package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer roleId;
     private Users users;
     private String roleName;
     private byte roleValue;

    public Roles() {
    }

    public Roles(Users users, String roleName, byte roleValue) {
       this.users = users;
       this.roleName = roleName;
       this.roleValue = roleValue;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public byte getRoleValue() {
        return this.roleValue;
    }
    
    public void setRoleValue(byte roleValue) {
        this.roleValue = roleValue;
    }




}


