package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seasons generated by hbm2java
 */
public class Seasons  implements java.io.Serializable {


     private Integer seasonId;
     private String seasonName;
     private Set modelses = new HashSet(0);

    public Seasons() {
    }

	
    public Seasons(String seasonName) {
        this.seasonName = seasonName;
    }
    public Seasons(String seasonName, Set modelses) {
       this.seasonName = seasonName;
       this.modelses = modelses;
    }
   
    public Integer getSeasonId() {
        return this.seasonId;
    }
    
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }
    public String getSeasonName() {
        return this.seasonName;
    }
    
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName;
    }
    public Set getModelses() {
        return this.modelses;
    }
    
    public void setModelses(Set modelses) {
        this.modelses = modelses;
    }




}


