package hibernate.entities;
// Generated 12 oct. 2018 17:49:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Stocks generated by hbm2java
 */
@Entity
@Table(name="stocks"
    ,catalog="flyinpizzas_mdabase"
    , uniqueConstraints = @UniqueConstraint(columnNames={"stock_article_id", "stock_place_id"}) 
)
public class Stocks  implements java.io.Serializable {


     private Integer stockId;
     private Articles articles;
     private Places places;
     private int stockQty;

    public Stocks() {
    }

    public Stocks(Articles articles, Places places, int stockQty) {
       this.articles = articles;
       this.places = places;
       this.stockQty = stockQty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="stock_id", unique=true, nullable=false)
    public Integer getStockId() {
        return this.stockId;
    }
    
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock_article_id", nullable=false)
    public Articles getArticles() {
        return this.articles;
    }
    
    public void setArticles(Articles articles) {
        this.articles = articles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock_place_id", nullable=false)
    public Places getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Places places) {
        this.places = places;
    }

    
    @Column(name="stock_qty", nullable=false)
    public int getStockQty() {
        return this.stockQty;
    }
    
    public void setStockQty(int stockQty) {
        this.stockQty = stockQty;
    }




}


