package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1



/**
 * Stocks generated by hbm2java
 */
public class Stocks  implements java.io.Serializable {


     private Integer stockId;
     private Articles articles;
     private Places places;
     private int stockQty;

    public Stocks() {
    }

    public Stocks(Articles articles, Places places, int stockQty) {
       this.articles = articles;
       this.places = places;
       this.stockQty = stockQty;
    }
   
    public Integer getStockId() {
        return this.stockId;
    }
    
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }
    public Articles getArticles() {
        return this.articles;
    }
    
    public void setArticles(Articles articles) {
        this.articles = articles;
    }
    public Places getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Places places) {
        this.places = places;
    }
    public int getStockQty() {
        return this.stockQty;
    }
    
    public void setStockQty(int stockQty) {
        this.stockQty = stockQty;
    }




}


