package hibernate.entities;
// Generated 8 nov. 2018 10:45:47 by Hibernate Tools 4.3.1

import hibernate.util.BCrypt;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private int userRole;
     private String userPassword;
     private Roles roles;

    public Users() {
    }

	
    public Users(String userName, int userRole, String userPassword) {
        this.userName = userName;
        this.userRole = userRole;
        this.userPassword = userPassword;
    }
    public Users(String userName, int userRole, String userPassword, Roles roles) {
       this.userName = userName;
       this.userRole = userRole;
       this.userPassword = userPassword;
       this.roles = roles;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public int getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(int userRole) {
        this.userRole = userRole;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        //this.userPassword = BCrypt.hashpw(userPassword, BCrypt.gensalt(12));
        this.userPassword = userPassword;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
 


}


